// A rolling record of requests made from this machine.
//
// Why local rather than fetched: the gateway's usage ledger stores per-day
// aggregates per account (tokens, requests, latency sums, per-model breakdowns)
// and deliberately not per-request rows — see backend/src/usage-stats.js. So
// there is no server-side "last 20 requests" to ask for. Rather than show an
// empty Logs tab or invent a server feature, this records what this CLI itself
// did, which is the thing a developer debugging their own session actually wants.
//
// The Usage tab remains the account-wide view; the two are labelled so they are
// not mistaken for each other.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { configDir } from "../platform.js";

export interface RequestLogEntry {
  id: string;
  /** ISO timestamp. */
  at: string;
  model: string;
  ok: boolean;
  latencyMs: number;
  /** Total tokens when the provider reported usage, else null. */
  tokens: number | null;
  /** Short reason when ok is false. */
  error?: string;
}

/** Enough to be useful, small enough that the file stays trivial to read. */
const MAX_ENTRIES = 200;

function logPath(): string {
  return path.join(configDir(), "requests.json");
}

export function loadRequestLog(): RequestLogEntry[] {
  try {
    const p = logPath();
    if (!existsSync(p)) return [];
    const parsed = JSON.parse(readFileSync(p, "utf8"));
    return Array.isArray(parsed) ? (parsed as RequestLogEntry[]) : [];
  } catch {
    // A corrupt log is not worth a crash, and not worth a warning either —
    // it holds nothing that cannot be regenerated by using the tool.
    return [];
  }
}

/**
 * Append one entry and persist. Returns the new list so callers can hold it in
 * state without re-reading the file.
 *
 * Best-effort on write: losing a log line must never fail the request it
 * describes, which has already been answered by the time this runs.
 */
export function appendRequestLog(entry: Omit<RequestLogEntry, "id" | "at">): RequestLogEntry[] {
  const next: RequestLogEntry[] = [
    ...loadRequestLog(),
    {
      ...entry,
      id: `req_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`,
      at: new Date().toISOString(),
    },
  ].slice(-MAX_ENTRIES);

  try {
    const dir = configDir();
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(logPath(), JSON.stringify(next, null, 2), "utf8");
  } catch {
    /* ignore */
  }

  return next;
}
